# Snowshoe hares at Bonanza Creek Experimental Forest
## Week 3 - Discussion section
### Snowshoe hares (Lepus americanus) in the Bonanza Creek Experimental Forest located in Alaska, USA.

In this discussion section, you will:

- Practice markdown syntax for creating tables and inserting images
- Practice detecting and cleaning messy data
- Use groupby() to calculate summary statistics by groups
- Select, clean, and comment your code to create a condensed data analysis workflow

### About the data

For these exercises we will use data about Snowshoe hares (Lepus americanus) in the [Bonanza Creek Experimental Forest](https://portal.edirepository.org/nis/mapbrowse?packageid=knb-lter-bnz.55.22).

This dataset is stored in the [Environmental Data Initiative (EDI)](https://edirepository.org/) data repository. This is a huge data repository committed to making data Findable, Accessible, Interoperable, and Reusable (FAIR). It is the main repository for all the data associated with the [Long Term Ecological Research Network (LTER)](https://lternet.edu/).

In [1]:
import pandas as pd

hares = pd.read_csv("55_Hare_Data_2012.txt")

In [6]:
hares.describe() # seeing the mean

            weight       hindft        b_key   session_id
count  2845.000000  1633.000000  3333.000000  3380.000000
mean   1346.081547   130.872627   500.640864    53.232249
std     345.160112    16.155295   299.421121    33.171355
min       0.000000    60.000000     1.000000     1.000000
25%    1180.000000   128.000000   235.000000    22.000000
50%    1400.000000   135.000000   464.000000    55.000000
75%    1580.000000   140.000000   755.000000    82.000000
max    2365.000000   160.000000  1034.000000   113.000000

hares.info()

In [12]:
hares

,date,time,grid,trap,l_ear,r_ear,sex,age,weight,hindft,notes,b_key,session_id,study
0,11/26/1998,NaN,bonrip,1A,414D096A08,NaN,NaN,NaN,1370.0,160.0,NaN,917.0,51,Population
1,11/26/1998,NaN,bonrip,2C,414D320671,NaN,M,NaN,1430.0,NaN,NaN,936.0,51,Population
2,11/26/1998,NaN,bonrip,2D,414D103E3A,NaN,M,NaN,1430.0,NaN,NaN,921.0,51,Population
3,11/26/1998,NaN,bonrip,2E,414D262D43,NaN,NaN,NaN,1490.0,135.0,NaN,931.0,51,Population
4,11/26/1998,NaN,bonrip,3B,414D2B4B58,NaN,NaN,NaN,1710.0,150.0,NaN,933.0,51,Population
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3375,8/8/2002,18:00:00,bonrip,1b,1201,1202,NaN,NaN,1400.0,NaN,NaN,63.0,64,Population
3376,8/8/2002,6:00:00,bonrip,4b,1201,1202,NaN,NaN,NaN,NaN,NaN,63.0,64,Population
3377,8/7/2002,NaN,bonrip,4b,1217,1218,NaN,NaN,1000.0,134.0,NaN,69.0,64,Population
3378,8/8/2002,NaN,bonrip,6d,1217,1218,NaN,NaN,990.0,NaN,NaN,69.0,64,Population
3379,8/6/2002,NaN,bonrip,4b,1058,1060,M,NaN,1460.0,119.0,NaN,32.0,64,Population

### Archive exploration
  
The Bonzana Creek LTER team assembled the data and was gathered since hares are keystone prey species. One row represents data from the capture-recpature study. The observations were collected  n the Tanana valley, from Tok in the east to Clear in the west from 1999 to 2002. The units for the hares' weight is in grams. As for missing data, all that is shown are NaN. This is still an ongoing study.

**Citation:** 

K. Kielland, F. S. Chapin, R. W. Ruess, and Bonanza Creek LTER, “Snowshoe hare physical data in Bonanza Creek Experimental Forest: 1999-Present.” Environmental Data Initiative, 2017. doi: 10.6073/PASTA/03DCE4856D79B91557D8E6CE2CBCDC14. [Available here](https://portal.edirepository.org/nis/mapbrowse?packageid=knb-lter-bnz.55.22). [Accessed: Oct. 16, 2024]

In [2]:
![hare](https://thumb.wikimedia.org/wikipedia/commons/thumb/8/8a/SNOWSHOE_HARE_%28Lepus_americanus%29_%285-28-2015%29_quoddy_head%2C_washington_co%2C_maine_-01_%2818988734889%29.jpg/1920px-SNOWSHOE_HARE_%28Lepus_americanus%29_%285-28-2015%29_quoddy_head%2C_washington_co%2C_maine_-01_%2818988734889%29.jpg?utm_source=commons.wikimedia.org&utm_campaign=index&utm_content=thumbnail&_=20170313021652)

/bin/bash: -c: line 1: syntax error near unexpected token `https://thumb.wikimedia.org/wikipedia/commons/thumb/8/8a/SNOWSHOE_HARE_%28Lepus_americanus%29_%285-28-2015%29_quoddy_head%2C_washington_co%2C_maine_-01_%2818988734889%29.jpg/1920px-SNOWSHOE_HARE_%28Lepus_americanus%29_%285-28-2015%29_quoddy_head%2C_washington_co%2C_maine_-01_%2818988734889%29.jpg?utm_source=commons.wikimedia.org'
/bin/bash: -c: line 1: `[hare](https://thumb.wikimedia.org/wikipedia/commons/thumb/8/8a/SNOWSHOE_HARE_%28Lepus_americanus%29_%285-28-2015%29_quoddy_head%2C_washington_co%2C_maine_-01_%2818988734889%29.jpg/1920px-SNOWSHOE_HARE_%28Lepus_americanus%29_%285-28-2015%29_quoddy_head%2C_washington_co%2C_maine_-01_%2818988734889%29.jpg?utm_source=commons.wikimedia.org&utm_campaign=index&utm_content=thumbnail&_=20170313021652)'

### Data loading and preliminary exploration

Using pandas methods, obtain preliminary information and explore this data frame. Consider answering some of these questions:

- What are the dimensions of the data frame and what are the data types of the columns?
  The dimension of the data is 3380 rows and 14 columns. The data types for the column are mostly object with 3 flots, and 1 int.
- Do the data types match what you would expect from each column?
  The columns for the date through age, I would expect string, instead there are object types.
- Are there any columns that have a significant number of NA values?
  The columns that have the most NA values are data, grid, and trap.
- What are the minimum and maximum values for the weight and hind feet measurements?
- What are the unique values for some of the categorical columns?
- Did any of the issues you anticipated in 1c show up?

In [3]:
hares.shape

(3380, 14)

In [4]:
hares.dtypes

date           object
time           object
grid           object
trap           object
l_ear          object
r_ear          object
sex            object
age            object
weight        float64
hindft        float64
notes          object
b_key         float64
session_id      int64
study          object
dtype: object

In [5]:
hares.count()

date          3380
time           264
grid          3380
trap          3368
l_ear         3332
r_ear         3211
sex           3028
age           1269
weight        2845
hindft        1633
notes          243
b_key         3333
session_id    3380
study         3217
dtype: int64

In [7]:
hares['weight'].max()

2365.0

In [8]:
hares['weight'].min()

0.0

In [9]:
hares['hindft'].max()

160.0

In [10]:
hares['hindft'].min()

60.0

In [11]:
hares.nunique()

date           256
time           165
grid             5
trap           121
l_ear         1020
r_ear          963
sex             12
age             30
weight         266
hindft          90
notes          118
b_key         1026
session_id     113
study            4
dtype: int64